### ISSUE TITLE
PHP 7.4.13 / php_interbase_nts_7.4.13.dll incompatibility

### ISSUE THREAD

**Issue by mnewnham** [FirebirdSQL/php-firebird#13]
When using the latest version of the Win x64 build of PHP interbase driver, the following startup error occurs

````
Warning: PHP Startup: Can't load module 'c:/dev/php-7.4.13/ext\php_interbase-7.4.13-nts.dll' 
as it's linked with 14.28, but the core is linked with 14.16 in Unknown on line 0
PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:30) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
````

I believe this is connected to the MSVC compiler version that the Firebird driver is built with

**Comment by MartinKoeditz** [comment]
Well, you're right. The latest driver is built with VS 2019. Should be 2017. I will rebuild it this weekend.

**Comment by mnewnham** [comment]
There are no Windows assets in the 1.1.1 build

**Comment by mnewnham** [comment]
Release 1.1.1 Windows drivers 7.4.16 are still being built with the wrong version of VC

**Comment by MartinKoeditz** [comment]
I compiled with the wrong VS version (again). I added a hint on the readme to avoid that in future. 

I replaced the assets. So please have a try.
