### ISSUE TITLE
Not working for PHP 7.2.24

### ISSUE THREAD

**Issue by boogiefromzk** [FirebirdSQL/php-firebird#17]
After compiling, and installing, I receive following error:
/usr/lib64/php/modules/interbase.so (/usr/lib64/php/modules/interbase.so: undefined symbol: zend_register_persistent_resource)) in Unknown on line 0
This is the default PHP version for CentOS 8

**Comment by mariuz** [comment]
zend_register_persistent_resource is from php 7.3 so this driver requires php 7.3 minimum 

you can use/compile the driver that comes with php 7.2 from centos (at that time driver was still in php source tree)

This can be closed
