### ISSUE TITLE
Driver not works with Firebird 1.5.6 on Win10 x64

### ISSUE THREAD

**Issue by Mepcuk** [FirebirdSQL/php-firebird#21]
I compiled driver using VS2017 tool X64 Native Tools Command Promt form VS2017 with installed Firebird 1.5.6, however compiled dll file not works.
`buildconf --force && configure --disable-all --enable-cli --with-interbase="shared,C:\Program Files\Firebird1_5\bin" && nmake`
 Maybe because Firebird 1.5 is 32-bit version or problem is Firebird do not have Lib folder only bin. Try to compile with "C:\Program Files\Firebird1_5" (without bin) - result no luck php did not see php_interbase.dll, however it is included in php/ext directory
Now like in your instruction i was removed Firebird1.5, dll's and after reboot installed Firebird 3.0. There are Lib directory, it compiled and `php -m` show interbase module without any error however now problem that i need to work with legacy Firebird 1.5 via PHP i got error message -> 

 php -r "ibase_connect ('localhost:/Noom/Data/noom.fdb', 'SYSDBA', 'masterkey', 'ISO8859_1', '100', '3' ) ;"
PHP Warning:  ibase_connect(): unsupported on-disk structure for file C:\NOOM\DATA\NOOM.FDB; found 10.1, support 12.2 IProvider::attachDatabase failed when loading mapping cache  in Command line code on line 1

That mean that driver support only Firebird 3.0 = Version 12.2

How to compile PHP driver for Firebird 1.5 ? How to include correct libraries from Firebird 1.5? Any suggestions?

**Comment by AlexPeshkoff** [comment]
On 7/26/21 5:25 PM, Maksims Alekseicevs wrote:


> How to compile PHP driver for Firebird 1.5 ? How to include correct 
> libraries from Firebird 1.5? Any suggestions?
>

The best solution is to upgrade ~20-years old firebird version.

**Comment by Mepcuk** [comment]
> On 7/26/21 5:25 PM, Maksims Alekseicevs wrote: How to compile PHP driver for Firebird 1.5 ? How to include correct libraries from Firebird 1.5? Any suggestions?
> The best solution is to upgrade ~20-years old firebird version.

It is legacy project - I can not do this :( App was written 20 years ago with old Deplhi and use legacy database Firebird1.5.6 and supported till now .... I just need to update Database from Web :)

**Comment by mrotteveel** [comment]
A Firebird 3.0 fbclient.dll should have no problem connecting to Firebird 1.5 server over TCP/IP. However, the error suggests you're trying to open a Firebird 1.5 database using Firebird 3.0.

**Comment by MartinKoeditz** [comment]
What Firebird server version do you use? What are your local fbclient.dlls?
The Firebird client dll we use in PHP is 3.0. Maybe it's the reaseon for the error message.

**Comment by Mepcuk** [comment]
Hello, i found precompiled php5.6 which work well wit fb1.5. I can not
successefully bild php with fb1.5. Php7+ requires fb2.5 or 3.0 and compile
with error.

пт, 1 окт. 2021 г., 16:30 Martin Köditz ***@***.***>:

**Comment by MartinKoeditz** [comment]
Yes, the dependencies in PHP are the main problem. For the compiliation we need fbclient 3.

So FB 1.5 is not really usable with PHP 7.

**Comment by AlexPeshkoff** [comment]
On 10/1/21 4:45 PM, Martin Köditz wrote:
>
> Yes, the dependencies in PHP are the main problem. For the 
> compiliation we need fbclient 3.
>
> So FB 1.5 is not really usable with PHP 7.
>

And it should not be usable!
What's a need to combine fresh PHP with >15(!!!) years old database ?

**Comment by Mepcuk** [comment]
I try compily with fb3 buuuuuut, build in driver can not open fb1.5.
Because fb1.5, 2.5, 3.0 have different structure.......

So to support my legacy project via web, i create manualy on php5.6 api. I
connect to api with Symfony5.3 and work as well. Of course some features
not available on php5.6 buuut it's works like a charm

пт, 1 окт. 2021 г., 16:45 Martin Köditz ***@***.***>:
