### ISSUE TITLE
interbase3.0.8.so php8.1 source

### ISSUE THREAD

**Issue by remco-pc** [FirebirdSQL/php-firebird#36]
where can i find the interbase3.0.8.so or how can i create it for php8.1 on the website i only see a php 7.4 version available

**Comment by satwareAG-ironMike** [comment]
If you need the Linux interbase.so file you can use this gist to build the module: cd /usr/src/php/ext/interbase
https://gist.github.com/satwareAG-ironMike/77ec10f912e3701966dc432913c56561

It uses docker and builts the artefacts for the 3.0.0 Version of the driver.

Currently I'm investigating 4 minor errors that make test casts but driver works well in my doctrine driver for firebird 3 (passes all tests there).

**Comment by MartinKoeditz** [comment]
You can find current linux versions in the release area [https://github.com/FirebirdSQL/php-firebird/releases](url).
Windows builds will follow next week.

**Comment by remco-pc** [comment]
i've compiled it myself
