### ISSUE TITLE
PHP_MD5Init could not be located in the dynamic link library for driver php_8.2.0-interbase-3.0.1-win-x64-ts.dll

### ISSUE THREAD

**Issue by buhlerax** [FirebirdSQL/php-firebird#46]
Driver not load.
The procedure entry point PHP_MD5Init could not be located in the dynamic link library for driver php_8.2.0-interbase-3.0.1-win-x64-ts.dll

**Comment by MartinKoeditz** [comment]
This symbol have been removed in https://github.com/php/php-src/commit/110b4e90946b6d46864c54c0e15b7a0deb6ad4b3

I recompiled the libs. Now they work.

**Comment by buhlerax** [comment]
Thanks
