### ISSUE TITLE
ibase_connect  Interbase Remote connection rejected by remote interface

### ISSUE THREAD

**Issue by jasonwu513** [FirebirdSQL/php-firebird#49]
Environment :   

InberBase2020 
 OS:  windows server 2019

App Server OS: Ubuntu 22.04
php: 8.1.2 
php-firebird :  php_8.1.13-interbase-3.0.1-linux-x64.so

```php
<?php

$dbh = ibase_connect('xxx.xxx.xxx.xxx:D:\workspace\DB\TEST2.IB', 'SYSDBA', 'masterkey');
```

return  PHP Warning:  ibase_connect(): connection rejected by remote interface

while I can use python ODBC to connect on windows plateform ,

```
...
connection_string = f'DRIVER=InterBase ODBC driver;DBNAME=10.10.99.11:D:\workspace\DB\TEST2.IB;UID={user};PWD={password};'

print(connection_string)
# Connect to the server
connection = pyodbc.connect(connection_string)

# Create a cursor
cursor = connection.cursor()
...
```

Can somebody  help?

**Comment by AlexPeshkoff** [comment]
Suppose you should better ask Embarcadero if you use Interbase.
