### ISSUE TITLE
Compilation errors / local path got included (?)

### ISSUE THREAD

**Issue by TimStollberg** [FirebirdSQL/php-firebird#61]
Hey guys,

i think in the last commit a small mistake happened. Some local paths got in the commit. See:

https://github.com/FirebirdSQL/php-firebird/commit/d59779b309cb74323dca8d2ef2ec95509f4e0acf

<img width="853" alt="image" src="https://github.com/user-attachments/assets/7e98c631-19e5-43fd-a918-fa2963b061f5">

I can't compile the source code anymore:

`3.900 config.status: creating config.h
3.926 make: *** No rule to make target '/home/koeditzm/Entwicklung/php-firebird/interbase.c', needed by 'interbase.lo'.  Stop.
`

Cheers Tim

**Comment by MartinKoeditz** [comment]
You're damn right. I wasn't paying attention. I removed the .dep files. Should work now. Please try again.

**Comment by TimStollberg** [comment]
It works again @MartinKoeditz 

Thank you!
