### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by faca5** [FirebirdSQL/php-firebird#8]
Hello.

Is possible to get "php_interbase.dll" and "fbclient.dll,gds32.dll" for PHP 8.0.0?

Thank you.

**Comment by MartinKoeditz** [comment]
Hi,

I missed PHP 8 is out. I will try to provide binaries this weekend.

Regards
Martin

**Comment by faca5** [comment]
Hello.

Thank you very much!

**Comment by MartinKoeditz** [comment]
Firebird extension for PHP 8.0.0 is available for Linux x64.
[https://firebirdsql.org/en/php-driver/](url)

Due to the lack of enough server space, the Windows build won't be available this weekend. But I'm sure I can build it tomorrow.

**Comment by MartinKoeditz** [comment]
Hi faca5,

I just added the PHP 8 extensions for Windows. Please have a look and give some feedback.

Thank you.

**Comment by mrotteveel** [comment]
@MartinKoeditz I'm curious, why publish the binaries on the Firebird host, and not on GitHub? Publishing on GitHub is what is done for the binaries of Firebird itself, and for example for Jaybird. The added benefit is that the download is backed by a CDN.

**Comment by MartinKoeditz** [comment]
@mrotteveel Well, I didn't know it's possible and that we're doing that already. I will change the release process.

**Comment by faca5** [comment]
> 
> 
> Hello.
> 
> Thank you very much!

Hello.

It works perfect! Tested. Thank you.

**Comment by MartinKoeditz** [comment]
Great. Thank you for feedback.
